export const publicUniversities = [
  "University of Dhaka",
  "University of Rajshahi",
  "University of Chittagong",
  "Jahangirnagar University",
  "Islamic University, Bangladesh",
  "Khulna University",
  "Jagannath University",
  "National University",
  "Bangladesh Open University",
  "Bangladesh University of Engineering and Technology (BUET)",
  "Chittagong University of Engineering and Technology (CUET)",
  "Rajshahi University of Engineering and Technology (RUET)",
  "Khulna University of Engineering and Technology (KUET)",
  "Dhaka University of Engineering and Technology (DUET)",
  "Bangladesh Agricultural University",
  "Patuakhali Science and Technology University",
  "Sher-e-Bangla Agricultural University",
  "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
  "Sylhet Agricultural University",
  "Hajee Mohammad Danesh Science and Technology University",
  "Noakhali Science and Technology University",
  "Mawlana Bhashani Science and Technology University",
  "Jessore University of Science and Technology",
  "Pabna University of Science and Technology",
  "Khulna Agricultural University",
  "Chandpur Science and Technology University",
  "Habiganj Agricultural University",
  "Rangamati Science and Technology University",
  "Rabindra University, Bangladesh",
  "Sheikh Hasina University",
  "Bangabandhu Sheikh Mujibur Rahman Science & Technology University",
  "Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University",
  "Bangabandhu Sheikh Mujibur Rahman Digital University",
  "Bangabandhu Sheikh Mujibur Rahman Maritime University",
  "Sheikh Hasina University of Science and Technology",
  "Bangladesh University of Professionals (BUP)",
  "Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University",
  "Gopalganj University of Science and Technology",
  "Islamic Arabic University",
  "Rabindra University",
  "University of Global Village",
  "Barisal University",
  "Begum Rokeya University",
  "Kazi Nazrul Islam University",
  "Comilla University",
  "Brahmanbaria University",
  "Sheikh Sayera Khatun Medical College",
  "Rangpur Medical University",
  "Chittagong Medical University",
  "Rajshahi Medical University",
  "Sylhet Medical University",
  "Sheikh Hasina Medical University, Khulna",
  "Sheikh Hasina Medical University, Sylhet",
  "Sheikh Hasina University of Veterinary and Animal Sciences",
  "Bangabandhu Sheikh Mujibur Rahman Medical University",
  "Sheikh Fazilatunnesa Mujib University",
  "Khulna Khan Bahadur Ahsanullah University",
  "Bangladesh Institute of Science and Technology University",
  "University of Skill Enrichment and Technology",
  "Asian University for Women (Public Branch)",
] as const;

export const privateUniversities = [
  "North South University (NSU)",
  "Independent University, Bangladesh (IUB)",
  "BRAC University",
  "American International University-Bangladesh (AIUB)",
  "East West University (EWU)",
  "Ahsanullah University of Science and Technology (AUST)",
  "Daffodil International University (DIU)",
  "United International University (UIU)",
  "University of Asia Pacific (UAP)",
  "Stamford University Bangladesh",
  "Southeast University",
  "Primeasia University",
  "Eastern University",
  "University of Liberal Arts Bangladesh (ULAB)",
  "Green University of Bangladesh",
  "Bangladesh University",
  "City University",
  "Northern University Bangladesh",
  "State University of Bangladesh",
  "Bangladesh University of Business and Technology (BUBT)",
  "World University of Bangladesh",
  "International University of Business Agriculture and Technology (IUBAT)",
  "Dhaka International University",
  "Manarat International University",
  "Premier University",
  "International Islamic University Chittagong (IIUC)",
  "Southern University Bangladesh",
  "University of Development Alternative (UODA)",
  "Asian University of Bangladesh",
  "Bangladesh Islami University",
  "The People's University of Bangladesh",
  "Royal University of Dhaka",
  "University of South Asia",
  "Victoria University of Bangladesh",
  "The Millennium University",
  "Atish Dipankar University of Science & Technology",
  "ASA University Bangladesh",
  "East Delta University",
  "Leading University",
  "Britannia University",
  "Varendra University",
  "North East University Bangladesh",
  "Port City International University",
  "Sonargaon University",
  "Cox’s Bazar International University",
  "University of Global Village (Private Branch)",
  "Prime University",
  "Central Women’s University",
  "Canadian University of Bangladesh",
  "University of Information Technology and Sciences (UITS)",
  "Bangladesh Army International University of Science and Technology (BAIUST)",
  "Bangladesh Army University of Engineering & Technology (BAUET)",
  "Bangladesh Army University of Science and Technology (BAUST)",
  "Bangladesh Army University of Professionals (Private sector division)",
  "Exim Bank Agricultural University",
  "German University Bangladesh",
  "Hamdard University Bangladesh",
  "North Bengal International University",
  "Ishakha International University",
  "Fareast International University",
  "Feni University",
  "Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University (Private Branch)",
  "The International University of Scholars",
  "NPI University of Bangladesh",
  "CCN University of Science & Technology",
  "Rabindra Maitree University",
  "University of Creative Technology, Chittagong",
  "University of Skill Enrichment and Technology (Private)",
  "Ranada Prasad Shaha University",
  "Times University Bangladesh",
  "Z.H. Sikder University of Science and Technology",
  "European University of Bangladesh",
  "Northern University of Business & Technology, Khulna",
  "Bangladesh University of Business and Communication",
  "Khwaja Yunus Ali University",
  "Notre Dame University Bangladesh",
  "University of Science and Technology, Chittagong (USTC)",
  "Central University of Science and Technology",
  "Bangladesh University of Medical Science",
  "University of Information Technology, Barishal",
  "Dhaka International Medical College & University",
  "International Standard University (ISU)",
  "Bangladesh University of Communication and Journalism",
  "Microland University of Science and Technology",
  "Global University Bangladesh",
  "Sheikh Fazilatunnesa Mujib University (Private)",
  "Islamic University of Technology (IUT)",
  "Canadian University of Science and Technology",
  "North Western University",
  "Gono Bishwabidyalay",
  "Bangladesh Institute of Health Sciences University",
  "University of Brahmanbaria",
  "Chittagong Independent University",
  "First Capital University of Bangladesh",
  "Bangladesh Continental University",
  "ASA University of Health and Technology",
  "Greenstone University",
  "University of Modern Sciences",
  "Kazi Nazrul Islam University College (Private)",
  "South East Medical University",
  "R.P. Shaha University",
  "Bangladesh University of Life Sciences",
  "International Cultural University",
  "BGMEA University of Fashion and Technology (BUFT)",
  "Asian University for Women (Private Branch)",
  "UITS University",
  "University of Creative Technology",
] as const;
