import { useMemo, useState } from "react";
import { format, formatDistanceToNow } from "date-fns";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAdminCareerGuidance } from "@/hooks/useAdminCareerGuidance";
import { FileText, Inbox, Layers, GraduationCap, Sparkles } from "lucide-react";

type StudentFilterOption = "all" | string;
type TabKey = "overview" | "documents" | "assessments" | "recommendations";

const formatTimestamp = (value: unknown): string | null => {
  const date = typeof value === "object" && value && "toDate" in value ? value.toDate() : undefined;
  if (!date) return null;
  try {
    return format(date, "PP • p");
  } catch (error) {
    console.warn("formatTimestamp failed", error);
    return null;
  }
};

const formatRelative = (value: unknown): string | null => {
  const date = typeof value === "object" && value && "toDate" in value ? value.toDate() : undefined;
  if (!date) return null;
  try {
    return formatDistanceToNow(date, { addSuffix: true });
  } catch (error) {
    console.warn("formatRelative failed", error);
    return null;
  }
};

const emptyStateCopy: Record<TabKey, { title: string; body: string }> = {
  overview: {
    title: "No activity captured yet",
    body: "Once students upload documents, take assessments, and receive AI guidance, their records will appear here for review.",
  },
  documents: {
    title: "No documents uploaded",
    body: "Student resumes, transcripts, and supporting files will surface here along with OCR confidence when submitted.",
  },
  assessments: {
    title: "Assessments not generated",
    body: "AI quizzes and corresponding attempts will populate this table after a student triggers the assessment flow.",
  },
  recommendations: {
    title: "Recommendations pending",
    body: "Career pathways generated by the AI assistant will be listed here with flagged risks or opportunities.",
  },
};

export default function CareerEmployabilityPage() {
  const { documents, assessments, attempts, recommendations, studentIds, isLoading } = useAdminCareerGuidance();
  const [studentFilter, setStudentFilter] = useState<StudentFilterOption>("all");
  const [activeTab, setActiveTab] = useState<TabKey>("overview");

  const filteredDocuments = useMemo(
    () => (studentFilter === "all" ? documents : documents.filter((doc) => doc.userId === studentFilter)),
    [documents, studentFilter],
  );

  const filteredAssessments = useMemo(
    () => (studentFilter === "all" ? assessments : assessments.filter((item) => item.userId === studentFilter)),
    [assessments, studentFilter],
  );

  const filteredAttempts = useMemo(
    () => (studentFilter === "all" ? attempts : attempts.filter((item) => item.userId === studentFilter)),
    [attempts, studentFilter],
  );

  const filteredRecommendations = useMemo(
    () => (studentFilter === "all" ? recommendations : recommendations.filter((item) => item.userId === studentFilter)),
    [recommendations, studentFilter],
  );

  const incompleteDocuments = useMemo(
    () => filteredDocuments.filter((doc) => doc.ocrStatus !== "success"),
    [filteredDocuments],
  );

  const recentAssessment = filteredAssessments[0];
  const recentRecommendation = filteredRecommendations[0];

  const averageScore = useMemo(() => {
    if (!filteredAttempts.length) return null;
    const sum = filteredAttempts.reduce((acc, attempt) => acc + (attempt.score ?? 0), 0);
    return Math.round(sum / filteredAttempts.length);
  }, [filteredAttempts]);

  const summaryCards = [
    {
      label: "Documents analysed",
      value: filteredDocuments.length,
      subtitle: incompleteDocuments.length ? `${incompleteDocuments.length} awaiting OCR` : "All documents processed",
      icon: FileText,
    },
    {
      label: "Assessments generated",
      value: filteredAssessments.length,
      subtitle: recentAssessment?.createdAt ? `Last ${formatRelative(recentAssessment.createdAt)}` : "Awaiting generation",
      icon: Layers,
    },
    {
      label: "Quiz attempts",
      value: filteredAttempts.length,
      subtitle: averageScore !== null ? `${averageScore}% average score` : "No submissions recorded",
      icon: GraduationCap,
    },
    {
      label: "AI recommendations",
      value: filteredRecommendations.length,
      subtitle: recentRecommendation?.generatedAt
        ? `Latest ${formatRelative(recentRecommendation.generatedAt)}`
        : "Run assessment to unlock",
      icon: Inbox,
    },
  ];

  const hasAnyData =
    filteredDocuments.length + filteredAssessments.length + filteredAttempts.length + filteredRecommendations.length > 0;

  const currentEmptyCopy = emptyStateCopy[activeTab] ?? emptyStateCopy.overview;

  return (
    <div className="space-y-8">
      <Card className="border-border/60 bg-card/90 shadow-lg backdrop-blur-md">
        <CardHeader className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <CardTitle className="text-2xl">Career Guidance Review</CardTitle>
            <CardDescription className="max-w-xl">
              Audit student artefacts, quiz performance, and AI recommendations to keep interventions on track.
            </CardDescription>
          </div>
          <div className="flex w-full flex-col gap-2 lg:w-auto lg:flex-row lg:items-center">
            <div className="text-xs uppercase tracking-wide text-muted-foreground">Filter by learner</div>
            <Select value={studentFilter} onValueChange={(value) => setStudentFilter(value as StudentFilterOption)}>
              <SelectTrigger className="lg:w-[220px]">
                <SelectValue placeholder="All students" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All students</SelectItem>
                {studentIds.map((id) => (
                  <SelectItem key={id} value={id}>
                    {id}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {summaryCards.map((item) => (
            <div key={item.label} className="rounded-2xl border border-border/60 bg-background/80 p-4 shadow-sm">
              <div className="flex items-center justify-between text-sm text-muted-foreground">
                <span>{item.label}</span>
                <item.icon className="h-4 w-4 text-primary" />
              </div>
              <div className="mt-3 text-3xl font-semibold">{item.value}</div>
              <div className="mt-1 text-xs text-muted-foreground">{item.subtitle}</div>
            </div>
          ))}
        </CardContent>
      </Card>

      {isLoading ? (
        <div className="grid gap-6 lg:grid-cols-[2fr,1fr]">
          <Skeleton className="h-[420px] rounded-3xl" />
          <Skeleton className="h-[420px] rounded-3xl" />
        </div>
      ) : hasAnyData ? (
        <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as TabKey)} className="space-y-6">
          <TabsList className="w-full justify-start overflow-x-auto">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="documents">Documents</TabsTrigger>
            <TabsTrigger value="assessments">Assessments &amp; Attempts</TabsTrigger>
            <TabsTrigger value="recommendations">AI Recommendations</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <Card className="border-border/60 bg-card/90">
              <CardHeader>
                <CardTitle className="text-lg">Latest activity</CardTitle>
                <CardDescription>Preview the most recent actions across the guidance journey.</CardDescription>
              </CardHeader>
              <CardContent className="grid gap-4 lg:grid-cols-2">
                <div className="rounded-2xl border border-border/60 bg-background/80 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium">
                    <FileText className="h-4 w-4 text-primary" /> Recent document upload
                  </div>
                  <Separator className="my-3" />
                  {filteredDocuments[0] ? (
                    <div className="space-y-2 text-sm">
                      <div className="font-medium text-foreground">{filteredDocuments[0].filename}</div>
                      <div className="text-xs text-muted-foreground">{filteredDocuments[0].userId}</div>
                      <div className="text-xs text-muted-foreground">
                        {formatTimestamp(filteredDocuments[0].uploadedAt) ?? "Unknown timestamp"}
                      </div>
                      <Badge
                        variant={filteredDocuments[0].ocrStatus === "success" ? "secondary" : "outline"}
                        className="rounded-full px-2 py-0 text-[10px] uppercase tracking-wide"
                      >
                        {filteredDocuments[0].ocrStatus ?? "pending"}
                      </Badge>
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground">No recent uploads yet.</p>
                  )}
                </div>

                <div className="rounded-2xl border border-border/60 bg-background/80 p-4">
                  <div className="flex items-center gap-2 text-sm font-medium">
                    <Sparkles className="h-4 w-4 text-primary" /> Latest recommendation
                  </div>
                  <Separator className="my-3" />
                  {recentRecommendation ? (
                    <div className="space-y-2 text-sm">
                      <div className="font-semibold text-foreground">
                        {recentRecommendation.recommendations[0]?.careerName ?? "Career pathway"}
                      </div>
                      <div className="text-xs text-muted-foreground">{recentRecommendation.userId}</div>
                      <div className="text-xs text-muted-foreground">
                        {formatTimestamp(recentRecommendation.generatedAt) ?? "Unknown timestamp"}
                      </div>
                      {recentRecommendation.recommendations[0]?.recommendedSubjectsToStudy?.length ? (
                        <p className="text-xs text-muted-foreground">
                          Focus: {recentRecommendation.recommendations[0].recommendedSubjectsToStudy.join(", ")}
                        </p>
                      ) : null}
                    </div>
                  ) : (
                    <p className="text-sm text-muted-foreground">Run an assessment to generate an insight.</p>
                  )}
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/60 bg-card/90">
              <CardHeader>
                <CardTitle className="text-lg">Assessment attempts</CardTitle>
                <CardDescription>Monitor scoring trends and completion time.</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[320px]">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Student</TableHead>
                        <TableHead>Assessment</TableHead>
                        <TableHead>Score</TableHead>
                        <TableHead>Submitted</TableHead>
                        <TableHead>Duration</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredAttempts.map((attempt) => (
                        <TableRow key={`${attempt.userId}-${attempt.id}`} className="border-border/60">
                          <TableCell className="text-sm font-medium text-foreground">{attempt.userId}</TableCell>
                          <TableCell className="text-xs text-muted-foreground">{attempt.assessmentId}</TableCell>
                          <TableCell>
                            <Badge variant={attempt.score >= 70 ? "secondary" : "outline"} className="rounded-full px-2 py-0 text-[10px]">
                              {attempt.score}%
                            </Badge>
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground">
                            {formatTimestamp(attempt.submittedAt) ?? "Unknown"}
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground">
                            {Math.round(attempt.timeTakenSeconds / 60)} minutes
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </ScrollArea>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="documents">
            <Card className="border-border/60 bg-card/90">
              <CardHeader>
                <CardTitle className="text-lg">Document intake</CardTitle>
                <CardDescription>Review uploaded artefacts and OCR confidence.</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[400px]">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Filename</TableHead>
                        <TableHead>Student</TableHead>
                        <TableHead>Uploaded</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Confidence</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredDocuments.map((doc) => {
                        const uploadedAt = formatTimestamp(doc.uploadedAt);
                        const status = doc.ocrStatus ?? "pending";
                        const confidence = typeof doc.docConfidence === "number" ? `${doc.docConfidence}%` : "--";
                        return (
                          <TableRow key={`${doc.userId}-${doc.id}`} className="border-border/60">
                            <TableCell className="max-w-[220px] truncate text-sm font-medium text-foreground">
                              {doc.filename}
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">{doc.userId}</TableCell>
                            <TableCell className="text-xs text-muted-foreground">{uploadedAt ?? "Unknown"}</TableCell>
                            <TableCell>
                              <Badge
                                variant={status === "success" ? "secondary" : status === "failed" ? "destructive" : "outline"}
                                className="rounded-full px-2 py-0 text-[10px] uppercase tracking-wide"
                              >
                                {status}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">{confidence}</TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </ScrollArea>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="assessments">
            <Card className="border-border/60 bg-card/90">
              <CardHeader>
                <CardTitle className="text-lg">Assessments &amp; attempts</CardTitle>
                <CardDescription>Trace generated assessments and linked submissions.</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[400px]">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Assessment ID</TableHead>
                        <TableHead>Student</TableHead>
                        <TableHead>Created</TableHead>
                        <TableHead>Questions</TableHead>
                        <TableHead>Generated by AI</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredAssessments.map((assessment) => (
                        <TableRow key={`${assessment.userId}-${assessment.id}`} className="border-border/60">
                          <TableCell className="text-sm font-medium text-foreground">{assessment.id}</TableCell>
                          <TableCell className="text-xs text-muted-foreground">{assessment.userId}</TableCell>
                          <TableCell className="text-xs text-muted-foreground">
                            {formatTimestamp(assessment.createdAt) ?? "Unknown"}
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground">{assessment.questions.length}</TableCell>
                          <TableCell>
                            <Badge variant={assessment.generatedByAI ? "secondary" : "outline"} className="rounded-full px-2 py-0 text-[10px]">
                              {assessment.generatedByAI ? "AI generated" : "Manual"}
                            </Badge>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </ScrollArea>
              </CardContent>
            </Card>

            <Card className="border-border/60 bg-card/90">
              <CardHeader>
                <CardTitle className="text-lg">Attempt log</CardTitle>
                <CardDescription>Cross-check submissions against assessments.</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[320px]">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Student</TableHead>
                        <TableHead>Assessment</TableHead>
                        <TableHead>Score</TableHead>
                        <TableHead>Submitted</TableHead>
                        <TableHead>Time taken</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredAttempts.map((attempt) => (
                        <TableRow key={`attempt-${attempt.userId}-${attempt.id}`} className="border-border/60">
                          <TableCell className="text-sm font-medium text-foreground">{attempt.userId}</TableCell>
                          <TableCell className="text-xs text-muted-foreground">{attempt.assessmentId}</TableCell>
                          <TableCell>
                            <Badge variant={attempt.score >= 70 ? "secondary" : "outline"} className="rounded-full px-2 py-0 text-[10px]">
                              {attempt.score}%
                            </Badge>
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground">
                            {formatTimestamp(attempt.submittedAt) ?? "Unknown"}
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground">
                            {Math.round(attempt.timeTakenSeconds / 60)} minutes
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </ScrollArea>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="recommendations">
            <Card className="border-border/60 bg-card/90">
              <CardHeader>
                <CardTitle className="text-lg">AI recommendations</CardTitle>
                <CardDescription>Validate generated pathways and risk flags.</CardDescription>
              </CardHeader>
              <CardContent className="p-0">
                <ScrollArea className="h-[400px]">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Student</TableHead>
                        <TableHead>Assessment</TableHead>
                        <TableHead>Generated</TableHead>
                        <TableHead>Career focus</TableHead>
                        <TableHead>Confidence</TableHead>
                        <TableHead>Flags</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredRecommendations.map((item) => {
                        const primaryRecommendation = item.recommendations[0];
                        return (
                          <TableRow key={`${item.userId}-${item.id}`} className="border-border/60">
                            <TableCell className="text-sm font-medium text-foreground">{item.userId}</TableCell>
                            <TableCell className="text-xs text-muted-foreground">{item.assessmentId}</TableCell>
                            <TableCell className="text-xs text-muted-foreground">
                              {formatTimestamp(item.generatedAt) ?? "Unknown"}
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">
                              {primaryRecommendation?.careerName ?? "--"}
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">
                              {primaryRecommendation?.confidenceScore ? `${primaryRecommendation.confidenceScore}%` : "--"}
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">
                              {item.flags?.length ? item.flags.join(", ") : "--"}
                            </TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </ScrollArea>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      ) : (
        <Card className="border-border/60 bg-card/90">
          <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
            <Sparkles className="h-10 w-10 text-muted-foreground" />
            <div className="text-lg font-semibold">{currentEmptyCopy.title}</div>
            <p className="max-w-xl text-sm text-muted-foreground">{currentEmptyCopy.body}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
